version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devtest
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - cache:/data/cache

volumes:
  cache:
    driver: local
